# if you're seeing this, you need to write a config file!!
# put a file named `conf.toml' in the same directory as your executable and
# fill it out as the example is done here and then "uncomment" (remove #s from) 
# the lines to get this program sending scripts to firefox

refresh = 100

[[spell]]
site = "*.example.com/*"
dir = "sites/example"
